apiVersion: apps/v1
kind: Deployment
metadata:
 name: ibmbankassistantapp
 labels:
    app: ibmbankassistantapp
spec:
 replicas: 2
 selector:
    matchLabels:
      app: ibmbankassistantapp
 template:
    metadata:
       labels:
        app: ibmbankassistantapp
    spec:
      containers:
      - name: ibmbankassistantappservice
        image: us.icr.io/ibmperumf/ibmbankassistantimg
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
 name: ibmbankassistantapp
spec:
 type: NodePort
 selector:
   app: ibmbankassistantapp
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32076
 selector:
   app: ibmbankassistantapp
